fedor/admin_panel/urls.py
from django.urls import path
from .views import *

app_name = 'admin_panel'
urlpatterns = [
    path('page/', show_admin_page, name="show_admin_page"),
    path('user/create/page/', show_registration_page, name='show_registration_page'),
    path('user/create/', user_registrations, name='create_user'),
    path('user/update/page/<int:user_id>', show_edit_user_page, name='show_edit_user_page'),
    path('user/update/<int:user_id>', update_user_profile, name='update_user_profile'),
    path('user/delete/<int:user_id>', delete_user, name='delete_user'),
    path('schedule/add-page/', schedule_add_page, name='schedule_add_page'),
    path('schedule/add/', schedule_add, name='schedule_add'),
    path('schedule/list/', schedule_list, name='schedule_list'),
    path('schedule/remove/<int:schedule_id>', schedule_remove, name='schedule_remove'),
    path('schedule/update-page/<int:schedule_id>', schedule_update_page, name='schedule_update_page'),
    path('schedule/update/<int:schedule_id>', schedule_update, name='schedule_update'),
    path('task/schedule-list/', task_schedule_list_page, name='task_schedule_list_page'),
    path('task/add-page/', task_add_page, name='task_add_page'),
    path('task/add/algoritm/', task_add_algoritm, name='task_add_algoritm'),
    path('task/remove/<int:task_id>', task_remove, name='task_remove'),
    path('task/change-status/<int:task_id>', task_change_status, name='task_change_status'),
    path('task-user/list/', tasks_user_list, name='tasks_user_list')

]

fedor/api/urls.py
from django.urls import path
from graphene_django.views import GraphQLView
from schema import schema
from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    path('graphql/', csrf_exempt(GraphQLView.as_view(graphiql=True, schema=schema))),
]

fedor/auth_fedor/urls.py
from django.urls import path
from .views import *

app_name = 'auth_fedor'
urlpatterns = [
    path('login/', show_login_page, name="login_page"),
    path('login/on/', user_login, name='user_login'),
    path('logout/', user_logout, name='user_logout')
]

fedor/fedor/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import *

urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('auth/', include('auth_fedor.urls')),
    path('auto/', include('auto_matching.urls')),
    path('admin/', include('admin_panel.urls')),
    path('matching/', include('manual_matching.urls')),
    path('directory/', include('directory.urls')),
    path('analytic/', include('analytic.urls')),
    path('api/', include('api.urls')),
    re_path(r'^', index)
]

fedor/auth_fedor/views.py
import logging
from django.contrib import auth
from django.core.exceptions import PermissionDenied
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from django.shortcuts import render, redirect, HttpResponseRedirect

logger = logging.getLogger(__name__)

PATH_AUTH_JOINT_PAGE = 'auth_fedor/auth_joint_page.html'
REDIRECT_URL_AUTH_JOINT = 'auth_fedor:login_page'


def fedor_auth_for_ajax(func):
    """Декоратор проверки авторизации"""
    def wrapper(request):
        if request.user.is_authenticated:
            return func(request)
        else:
            raise PermissionDenied()

    return wrapper


def fedor_permit(perm=[1]):
    """Декоратор проверки авторизации и прав пользователя"""
    def wrapper(func):
        def permit(*args, **kwargs):
            request = args[0]
            if request.user.is_authenticated and request.user.profile.access_level.level in perm:
                return func(*args, **kwargs)
            else:
                if request.is_ajax():
                    raise PermissionDenied()
                else:
                    return redirect(REDIRECT_URL_AUTH_JOINT)

        return permit

    return wrapper


def show_login_page(request):
    """Показать страницу авторизации"""
    result = {'error': request.session.get('error')}
    return render(request, PATH_AUTH_JOINT_PAGE, result)


@require_http_methods(['POST'])
def user_login(request):
    """Авторизация пользователя"""
    res = {'username': request.POST.get('username'), 'password': request.POST.get('password')}
    user = auth.authenticate(username=res['username'], password=res['password'])
    if user:
        auth.login(request, user)
        logger.info('Авторизовался:{}'.format(request.user))
        return redirect('/matching/manual-matching/page/')
    else:
        logger.info('Ошибка авторизации {}'.format(res['username']))
        request.session['error'] = 'Неверно введены имя пользователя или пароль'
    return HttpResponseRedirect(
        reverse(REDIRECT_URL_AUTH_JOINT)
    )


def user_logout(request):
    """Деавторизация пользователя"""
    auth.logout(request)
    next_page = request.GET['next']
    return HttpResponseRedirect(next_page)

fedor/auth_fedor/templates/auth_fedor/auth_joint_page.html
{% extends "index.html" %}
{% block title %}Страница авторизации{% endblock %}
{% block content %}
	<div class="container" style="margin-top: 10%;">
		<div class="row">
			<div class="col s12 text-center">
				<h5>Авторизация</h5>
			</div>
		</div>
		<div class="row">
			<div class="col s8 offset-s4">
				<form method="post" action="{% url 'auth_fedor:user_login' %}?next={{next}}">
					{% csrf_token %}
					<div class="row">
						<div class="input-field col s6">
						  	<input placeholder="Логин" id="login" type="text" class="validate" name="username">
						  	<label for="login">Логин</label>
						</div>
					</div>
					<div class="row">
						<div class="input-field col s6">
						  	<input placeholder="Пароль" id="password" type="password" class="validate" name="password">
						  	<label for="password">Пароль</label>
							{% if error %}
								<p>{{ error }}</p>
							{% endif %}
						</div>
					</div>
					<div class="row">
						<div class="col s2">
							<button type="submit" class="btn btn-primary">Войти</button>
						</div>
						<div class="col s3 offset-s2">
							<a href="{% url 'admin_panel:show_registration_page' %}" type="submit" class="btn btn-primary">Регистрация</a>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
{% endblock %}
{% block script %}
{% endblock %}