fedor/admin_panel/urls.py
from django.urls import path
from .views import *

app_name = 'admin_panel'
urlpatterns = [
    path('page/', show_admin_page, name="show_admin_page"),
    path('user/create/page/', show_registration_page, name='show_registration_page'),
    path('user/create/', user_registrations, name='create_user'),
    path('user/update/page/<int:user_id>', show_edit_user_page, name='show_edit_user_page'),
    path('user/update/<int:user_id>', update_user_profile, name='update_user_profile'),
    path('user/delete/<int:user_id>', delete_user, name='delete_user'),
    path('schedule/add-page/', schedule_add_page, name='schedule_add_page'),
    path('schedule/add/', schedule_add, name='schedule_add'),
    path('schedule/list/', schedule_list, name='schedule_list'),
    path('schedule/remove/<int:schedule_id>', schedule_remove, name='schedule_remove'),
    path('schedule/update-page/<int:schedule_id>', schedule_update_page, name='schedule_update_page'),
    path('schedule/update/<int:schedule_id>', schedule_update, name='schedule_update'),
    path('task/schedule-list/', task_schedule_list_page, name='task_schedule_list_page'),
    path('task/add-page/', task_add_page, name='task_add_page'),
    path('task/add/algoritm/', task_add_algoritm, name='task_add_algoritm'),
    path('task/remove/<int:task_id>', task_remove, name='task_remove'),
    path('task/change-status/<int:task_id>', task_change_status, name='task_change_status'),
    path('task-user/list/', tasks_user_list, name='tasks_user_list')

]

fedor/api/urls.py
from django.urls import path
from graphene_django.views import GraphQLView
from schema import schema
from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    path('graphql/', csrf_exempt(GraphQLView.as_view(graphiql=True, schema=schema))),
]

fedor/fedor/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import *

urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('auth/', include('auth_fedor.urls')),
    path('auto/', include('auto_matching.urls')),
    path('admin/', include('admin_panel.urls')),
    path('matching/', include('manual_matching.urls')),
    path('directory/', include('directory.urls')),
    path('analytic/', include('analytic.urls')),
    path('api/', include('api.urls')),
    re_path(r'^', index)
]

fedor/admin_panel/models.py
from django.db import models
from django.contrib.auth.models import User
from directory.models import Competitors


class AccessLevel(models.Model):
    """Уровень доступа"""
    level = models.IntegerField()
    level_name = models.CharField(max_length=150)

    def __str__(self):
        return '{}'.format(self.level_name)

    # level 1 level_name Админ
    # level 2 level_name Суперюзер
    # level 3 level_name Сотрудник pharma.Global
    # level 4 level_name Аптека


class Profile(models.Model):
    """Профиль пользователя"""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    access_level = models.ForeignKey(AccessLevel, on_delete=models.CASCADE)
    competitor = models.ForeignKey(Competitors, models.SET_NULL, blank=True, null=True)


class Tasks(models.Model):
    """Пользовательские задачи"""
    task_id = models.CharField(max_length=500)
    name = models.TextField()
    status = models.CharField(max_length=500, blank=True)
    result = models.TextField(blank=True)
    create_date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, default=1)


class FedorLog(models.Model):
    message = models.TextField(blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    sku_id = models.BigIntegerField(blank=True, null=True)
    eas_id = models.BigIntegerField(blank=True, null=True)
    action = models.IntegerField()  # 1 мэтчинг, 2 запуск алгоритма, 3 массовые подмены, 4 планировщик
    create_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'fedor_log'
        ordering = ['-create_date']

fedor/admin_panel/services/forms/create_update_user_forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from directory.models import Competitors
from admin_panel.models import *


class CustomCreationForm(UserCreationForm):
    """Форма регистрации пользователя"""

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'password1']

    def save(self):
        user = super(CustomCreationForm, self).save(commit=True)
        Profile.objects.create(
            user=user,
            access_level=AccessLevel.objects.get(id=3))  # Права по умолчанию
        return user


class CustomUpdateUserForm(UserChangeForm):
    """Форма редактирования профиля пользователя"""

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

    def save(self, level_id, competitor=None):
        user = super(CustomUpdateUserForm, self).save(commit=True)
        access_level = AccessLevel.objects.get(level=level_id)
        try:
            profile = Profile.objects.get(user=user)
            profile.access_level = access_level
            profile.save()
            if competitor:
                competitor = Competitors.objects.get(pk=competitor)
                profile.competitor = competitor
                profile.save()
            else:
                profile.competitor = None
                profile.save()
        except Profile.DoesNotExist:
            Profile.objects.create(user=user, access_level=access_level)
        return user

fedor/admin_panel/services/forms/schedule_forms.py
from django import forms
from django_celery_beat.models import CrontabSchedule, PeriodicTask


class CrontabScheduleForm(forms.ModelForm):
    """Создание расписания"""
    class Meta:
        model = CrontabSchedule
        fields = ('minute', 'hour', 'day_of_week', 'month_of_year')

fedor/admin_panel/views.py
import operator
from datetime import datetime
from .services import fedor_log
from django.http import JsonResponse
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.views.decorators.http import require_http_methods
from django.urls import reverse
import logging
from .models import Tasks
from .services import user_manipulation
from django.contrib.auth.models import User
from auth_fedor.views import fedor_permit, fedor_auth_for_ajax
from directory.models import Competitors
import json
from django.db.models import Q
from django_celery_beat.models import CrontabSchedule, PeriodicTask
from .services.forms.schedule_forms import CrontabScheduleForm
from directory.services.directory_querys import get_number_competitor_list
from django_celery_results.models import TaskResult

logger = logging.getLogger(__name__)

"""Глобальные переменные шаблонов"""
REGISTRATION_PAGE_TEMPLATE_PATH = 'admin_panel/registration_page.html'
UPDATE_USER_PROFILE_TEMPLATE_PATH = 'admin_panel/edit_user.html'
ADMIN_PAGE_PATH = 'admin_panel/admin_page.html'
SCHEDULE_TEMPLATE = 'admin_panel/add_schedule.html'
SCHEDULE_LIST_TEMPLATE = 'admin_panel/schedule_list.html'
SCHEDULE_UPDATE_TEMPLATE = 'admin_panel/schedule_update.html'
TASK_LIST_SCHEDULE_TEMPLATE = 'admin_panel/task_list_schedule.html'
TASK_ADD_SCHEDULE_TEMPLATE = 'admin_panel/task_add.html'

"""Глобальные переменные урлов"""
SHOW_REGISTRATION_PAGE_URL = 'admin_panel:show_registration_page'
SHOW_UPDATE_USER_PROFILE_PAGE_URL = 'admin_panel:show_edit_user_page'
SCHEDULE_ADD_URL = 'admin_panel:schedule_page'
SCHEDULE_LIST_URL = 'admin_panel:schedule_list'
TASK_LIST_SCHEDULE_URL = 'admin_panel:task_schedule_list_page'


def show_registration_page(request):
    """Рендер интерфейса регистрации пользовтеля"""
    result = {'error': request.session.get('error')}
    return render(request, REGISTRATION_PAGE_TEMPLATE_PATH, result)


@require_http_methods(['POST'])
def user_registrations(request):
    """Регистрация пользователя"""
    user_id = user_manipulation.create_user(request.POST)
    if user_id:
        if request.user.is_authenticated:
            logger.debug('Пользователь успешно создан')
            return HttpResponseRedirect(
                reverse(SHOW_UPDATE_USER_PROFILE_PAGE_URL,
                        kwargs={'user_id': user_id})
            )
        else:
            return HttpResponseRedirect(
                reverse('auth_fedor:login_page')
            )
    request.session['error'] = 'Вы ввели невалидный пароль!'
    logger.debug('Не удалось создать пользователя')
    return HttpResponseRedirect(
        reverse(SHOW_REGISTRATION_PAGE_URL)
    )


@fedor_permit([1])
def show_edit_user_page(request, user_id):
    """Показывает интерфейс редактирования профиля"""
    logger.info('user_id: {}'.format(user_id))
    result = {
        'target_user': user_manipulation.get_user(user_id),
        'access_levels': user_manipulation.get_all_access_level(),
        'competitors': Competitors.objects.all(),
        'users': User.objects.all()
    }
    return render(request, UPDATE_USER_PROFILE_TEMPLATE_PATH, result)


@fedor_permit([1])
def update_user_profile(request, user_id):
    """Изменение профиля пользовтеля"""
    request.session['error'] = ''
    access_level = request.POST.get('access_level')
    competitor = request.POST.get('competitor')
    if user_manipulation.edit_user_profile(request.POST, user_id, access_level, competitor):
        logger.debug('Профиль успешно обновлен!')
        return HttpResponseRedirect(
            reverse(SHOW_UPDATE_USER_PROFILE_PAGE_URL,
                    kwargs={'user_id': user_id})
        )
    else:
        request.session['error'] = 'Не удалось внести изменения'
        logger.debug('Не удалось обновить профиль')
        return HttpResponseRedirect(
            reverse(SHOW_UPDATE_USER_PROFILE_PAGE_URL,
                    kwargs={'user_id': user_id})
        )


@fedor_permit([1])
def delete_user(request, user_id):
    """Удаление четной записи пользователя"""
    User.objects.get(pk=user_id).delete()
    return HttpResponseRedirect(
        reverse(SHOW_UPDATE_USER_PROFILE_PAGE_URL,
                kwargs={'user_id': User.objects.latest('pk').pk})
    )


@fedor_permit([1])
def show_admin_page(request):
    """Рендер страници администрирования"""
    return render(request, ADMIN_PAGE_PATH, {})


@fedor_permit([1])
def schedule_add_page(request):
    """Рендер страницы добавления расписания"""
    result = {}
    return render(request, SCHEDULE_TEMPLATE, result)


@fedor_permit([1])
def schedule_add(request):
    """Добавить расписание"""
    user = request.user
    request = json.loads(request.body.decode('utf-8'))
    time_start = request['data']['time']
    if time_start:
        time_start = datetime.strptime(time_start, '%H:%M')
        hour = time_start.hour
        minute = time_start.minute
        schedule, _ = CrontabSchedule.objects.get_or_create(
            minute=minute,
            hour=hour,
            day_of_week='*',
            day_of_month='*',
            month_of_year='*',
            timezone='Europe/Moscow'
        )
        fedor_log.log(
            user=user,
            message='Пользователь({}) - добавлено расписание - время({}:{})'.format(user, minute, hour),
            action=4  # 4 планировщик
        )
    return JsonResponse(True, safe=False)


@fedor_permit([1])
def schedule_remove(request, schedule_id):
    """Удалить расписание"""
    user = request.user
    CrontabSchedule.objects.get(pk=schedule_id).delete()
    fedor_log.log(
        user=user,
        message='Пользователь({}) - удаление расписания - id({})'.format(user, schedule_id),
        action=4  # 4 планировщик
    )
    return HttpResponseRedirect(
        reverse(SCHEDULE_LIST_URL)
    )


def string_converter(value):
    """Конвертирование даты в строку для json.dumps"""
    return str(value)


@fedor_permit([1])
def schedule_list(request):
    """Список расписаний"""
    if request.is_ajax():
        schedules = CrontabSchedule.objects.all().values('minute', 'hour', 'day_of_week', 'month_of_year', 'timezone',
                                                         'pk')
        schedules = json.dumps(list(schedules), default=string_converter)
        return JsonResponse(schedules, safe=False)
    require = {
        'schedules': CrontabSchedule.objects.all().order_by('-pk')
    }
    return render(request, SCHEDULE_LIST_TEMPLATE, require)


@fedor_permit([1])
def schedule_update_page(request, schedule_id):
    """Страница редактирования расписания"""
    require = {
        'schedule': CrontabSchedule.objects.get(pk=schedule_id)
    }
    return render(request, SCHEDULE_UPDATE_TEMPLATE, require)


@fedor_permit([1])
@require_http_methods(['POST'])
def schedule_update(request, schedule_id):
    """Изменение расписания"""
    user = request.user
    crontab_form = CrontabScheduleForm(request.POST, instance=CrontabSchedule.objects.get(pk=schedule_id))
    if crontab_form.is_valid():
        crontab_form.save()
        fedor_log.log(
            user=user,
            message='Пользователь({}) - изменение расписания - id({})'.format(user, schedule_id),
            action=4  # 4 планировщик
        )
        return HttpResponseRedirect(
            reverse(SCHEDULE_LIST_URL)
        )
    else:
        return HttpResponseRedirect(
            reverse(SCHEDULE_LIST_URL)
        )


@fedor_permit([1])
def task_schedule_list_page(request):
    """Страница задач"""
    require = {
        'tasks': PeriodicTask.objects.all().order_by('-total_run_count', '-pk'),
    }
    return render(request, TASK_LIST_SCHEDULE_TEMPLATE, require)


@fedor_permit([1])
def task_add_page(request):
    """Страница добавления задачи"""
    require = {
        'competitors': get_number_competitor_list(request.user),
    }
    return render(request, TASK_ADD_SCHEDULE_TEMPLATE, require)


@fedor_permit([1])
def task_add_algoritm(request):
    """Добавление в планировщик задач алгоритма"""
    user = request.user
    request = json.loads(request.body.decode('utf-8'))
    number_competitor_id = json.loads(request['data'].get('number_competitor_id'))
    name = request['data'].get('name')
    description = request['data'].get('description')
    crontab = request['data'].get('crontab')
    new_sku = request['data'].get('new_sku')
    action = request['data'].get('action')
    barcode_match = request['data'].get('barcode_match')
    task_status = request['data'].get('task_status')
    one_task_status = request['data'].get('one_task_status')
    selected_task = request['data'].get('selected_task')

    arguments = {
        'number_competitor_id': number_competitor_id,
        'new_sku': new_sku,
        'action': action,
        'barcode_match': barcode_match
    }
    PeriodicTask.objects.create(
        crontab=CrontabSchedule.objects.get(pk=crontab),
        name=name,
        description=description,
        task=selected_task,
        kwargs=json.dumps(arguments),
        enabled=task_status,
        one_off=one_task_status
    )
    fedor_log.log(
        user=user,
        message='Пользователь({}) - планирование запуска алгоритма - справочник({}) - акция({}) - довреять ШК({}) - '
                'новая  номенклатура({}) - имя задачи({})'.format(user, number_competitor_id, action, barcode_match,
                                                                  new_sku, name),
        action=4  # 4 - планировщик
    )
    return JsonResponse(True, safe=False)


@fedor_permit([1])
def task_remove(request, task_id):
    """Удаление задачи"""
    user = request.user
    p_task = PeriodicTask.objects.get(pk=task_id)
    fedor_log.log(
        user=user,
        message='Пользователь({}) - удаление задачи - id({}) - название({})'.format(user, task_id, p_task.name),
        action=4  # 4 планировщик
    )
    p_task.delete()
    return HttpResponseRedirect(
        reverse(TASK_LIST_SCHEDULE_URL)
    )


@fedor_permit([1])

fedor/admin_panel/templates/admin_panel/add_schedule.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
    {% include 'admin_panel/schedule.html'  %}
<div class="container" id="schedule_app">
    <div class="row fedor-schedule-form">
        <div class="col s6 offset-s4">
                <div class="row">
                    <div class="input-field col s6">
                        <input type="text" id="hour" class="timepicker" placeholder="Время" name="time" v-model.lazy="time">
                        <label for="hour">Время</label>
                    </div>
                </div>
                <div class="row">
                    <div class="col s2">
						<button class="btn btn-primary" v-on:click="create_schedule">Добавить</button>
					</div>
				</div>
        </div>
    </div>
</div>
{% endblock %}
{% block script %}
<script src="{% static 'admin_panel/js/schedule.js' %}"></script>
{% endblock %}

fedor/admin_panel/templates/admin_panel/admin_page.html
{% extends 'index.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col s12">

            </div>
        </div>
    </div>
{% endblock %}

fedor/admin_panel/templates/admin_panel/edit_user.html
{% extends 'index.html' %}
{% block content %}
	<div class="container f-mt">
		<div class="row">
			<div class="col s8">
				<div class="card">
					<div class="card-content white-text">
						<span class="card-title">Редактирование</span>
					<form method="post", action="{% url 'admin_panel:update_user_profile' user_id=target_user.pk %}">
						{% csrf_token %}
						<div class="row">
							<div class="input-field col s6">
								<input placeholder="Логин" id="login" type="text" class="validate" value="{{ target_user.username }}" name="username">
								<label for="login">Логин</label>
							</div>
						</div>
						<div class="row">
							<div class="input-field col s6">
								<input placeholder="Имя" id="first_name" type="text" class="validate" value="{{ target_user.first_name }}" name="first_name">
								<label for="first_name">Имя</label>
							</div>
						</div>
						<div class="row">
							<div class="input-field col s6">
								<input placeholder="Фамилия" id="last_name" type="text" class="validate" value="{{ target_user.last_name }}" name="last_name">
								<label for="last_name">Фамилия</label>
							</div>
						</div>
						<div class="row">
							 <div class="input-field col s6">
								<input placeholder="Почта" id="email" type="email" class="validate" value="{{ target_user.email }}" name="email">
								<label for="email">Почта</label>
							 </div>
						</div>
						<div class="row">
							<div class="input-field col s6">
								<select name="access_level">
									<option value="" disabled selected>Профили</option>
										{% for level in access_levels %}
											{% if level.level == target_user.profile.access_level.level %}
												<option value="{{ level.level }}" selected>{{ level.level_name }}</option>
											{% else %}
												<option value="{{ level.level }}">{{ level.level_name }}</option>
											{% endif %}
										{% endfor %}
								</select>
								<label>Профиль доступа</label>
							</div>
						</div>
						<div class="row">
							<div class="col s2">
								<button type="submit" class="btn btn-primary">Изменить</button>
							</div>
							<div class="col s1">
								<button type="submit" class="btn btn-danger" form="user-card-del">Удалить</button>
							</div>
						</div>
					</form>
					<form method="post" action="{% url 'admin_panel:delete_user' user_id=target_user.pk %}" id="user-card-del">{% csrf_token %}</form>
				</div>
				</div>
			</div>
			<div class="col s4 text-center">
				<h5>Список пользователей</h5>
				<div class="collection f-mt">
					{% for user in users %}
						{% if target_user.pk == user.pk %}
							<a href="{% url 'admin_panel:show_edit_user_page' user_id=user.pk %}" class="collection-item active">{{ user }}</a>
						{% else %}
							<a href="{% url 'admin_panel:show_edit_user_page' user_id=user.pk %}"  class="collection-item">{{ user }}</a>
						{% endif %}
					{% endfor %}
				</div>
			</div>
		</div>
	</div>
{% endblock %}
{% block script %}
<script>
	document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('select');
    var instances = M.FormSelect.init(elems);
  });
</script>
{% endblock %}

fedor/admin_panel/templates/admin_panel/registration_page.html
{% extends 'index.html' %}
{% block title %}Форма регистрации пользователя{% endblock %}
{% block content %}
<div class="container">
	<div class="row">
		<div class="col s12 text-center">
			<h5>Форма регистрации</h5>
		</div>
	</div>
	<div class="row">
		<div class="col s11 offset-s3">
			<form method="post", action="{% url 'admin_panel:create_user' %}">
				{% csrf_token %}
				<div class="row">
					<div class="input-field col s6">
					  <input placeholder="Логин" id="login" type="text" class="validate" name="username">
					  <label for="login">Логин</label>
					</div>
				</div>
				<div class="row">
					<div class="input-field col s6">
					  	<input placeholder="Пароль" id="password" type="password" class="validate" name="password1">
					  	<label for="password">Пароль</label>
						{% if error %}
						<p class="text-danger">{{ error }}</p>
						{% endif %}
					</div>
				</div>
				<div class="row">
					<div class="input-field col s6">
						<input placeholder="Повторите пароль" id="password2" type="password" class="validate" name="password2">
						<label for="password2">Повторите пароль</label>
					</div>
				</div>
				<div class="row">
					<div class="input-field col s6">
				  		<input placeholder="Имя" id="first_name" type="text" class="validate" name="first_name">
				  		<label for="first_name">Имя</label>
					</div>
				</div>
				<div class="row">
					<div class="input-field col s6">
					  	<input placeholder="Фамилия" id="last_name" type="text" class="validate" name="last_name">
					  	<label for="last_name">Фамилия</label>
					</div>
				</div>
				<button type="submit" class="btn btn-primary">Зарегистрировать</button>
			</form>

		</div>
	</div>
</div>
{% endblock %}

fedor/admin_panel/templates/admin_panel/schedule.html
<div class="row">
    <div class="col fedor-schedule-menu">
        <ul class="collection with-header">
        <li class="collection-header text-center"><h6>Планировщик задач</h6></li>
        <li class="collection-item">
            <div>
                <a href="{% url 'admin_panel:schedule_list' %}">ВРЕМЯ ЗАПУСКА</a>
                <a href="{% url 'admin_panel:schedule_add_page' %}" class="secondary-content"><i class="material-icons">add</i></a>
            </div>
        </li>
        <li class="collection-item">
            <div>
                <a href="{% url 'admin_panel:task_schedule_list_page' %}">ЗАДАЧИ</a>
                <a href="{% url 'admin_panel:task_add_page' %}" class="secondary-content"><i class="material-icons">add</i></a>
            </div>
        </li>
      </ul>
    </div>
</div>

{% block script %}
<script>
	document.addEventListener('DOMContentLoaded', function() {
    var collapsible = document.querySelectorAll('.collapsible');
    var instances = M.Collapsible.init(collapsible);
  });
</script>
{% endblock %}

fedor/admin_panel/templates/admin_panel/schedule_list.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
    {% include 'admin_panel/schedule.html'  %}
    <div class="container">
        <div class="row">
            <div class="col s6 offset-s3">
                <table class="collection fedor-table">
                    <thead>
                        {% for schedule in schedules %}
                            <tr>
                                <th class="collection-item">
                                    <a href="{% url 'admin_panel:schedule_update_page' schedule.pk %}">
                                        {{schedule.hour}}:{{schedule.minute}} День недели:{{schedule.day_of_week}} Месяц:{{schedule.month_of_year}}
                                    </a></th>
                                <th class="collection-item"><a href="{% url 'admin_panel:schedule_remove' schedule.pk %}">
                                    <i class="material-icons  deep-orange-text accent-3">remove</i>
                                </a></th>
                            </tr>
                        {% endfor %}
                    </thead>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

fedor/admin_panel/templates/admin_panel/schedule_update.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
    {% include 'admin_panel/schedule.html'  %}
    <div class="container">
        <div class="row fedor-schedule-form">
            <div class="col s6 offset-s4">
                <form method="post" action="{% url 'admin_panel:schedule_update' schedule_id=schedule.pk %}">
                    {% csrf_token %}
                    <div class="row">
                        <div class="input-field col s6">
                            <input type="text" id="min" placeholder="Минута" name="minute" value="{{ schedule.minute }}">
                            <label for="min">Минута</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s6">
                            <input type="text" id="hour" placeholder="Час" name="hour" value="{{ schedule.hour }}">
                            <label for="hour">Час</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s6">
                            <input type="text" id="day_of_week" placeholder="Дни недели" name="day_of_week" value="{{ schedule.day_of_week }}">
                            <label for="day_of_week">Дни недели</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s6">
                            <input type="text" id="month_of_year" placeholder="Месяца" value="{{ schedule.month_of_year }}" name="month_of_year">
                            <label for="month_of_year">Месяца</label>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col s2">
                            <button type="submit" class="btn btn-primary">Изменить</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

fedor/admin_panel/templates/admin_panel/task_list_schedule.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
    {% include 'admin_panel/schedule.html'  %}
        <div class="row">
            <div class="col l10 offset-l2">
                <div class="card">
                    <div class="card-content">
                        <span class="card-title text-center">Задачи</span>
                        <table style="font-size: 12px;" class="centered">
                            <thead>
                            <tr>
                                <th class="text-center">ИМЯ</th>
                                <th class="text-center">ЗАДАЧА</th>
                                <th class="text-center">ОПИСАНИЕ</th>
                                <th class="text-center">СТАТУС</th>
                                <th class="text-center">ВРЕМЯ ЗАПУСКА</th>
                                <th class="text-center">ПОСЛЕДНИЙ ЗАПУСК</th>
                                <th class="text-center">СЧЕТЧИК ЗАПУСКОВ</th>
                                <th class="text-center">ОДНОРАЗОВЫЙ ЗАПУСК</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                                {% for task in tasks %}
                                <tr>
                                    <th class="text-center">{{task.name}}</th>
                                    <th class="text-center">{{task.task}}</th>
                                    <th class="text-center">{{task.description}}</th>
                                    {% if task.enabled == True %}
                                        <th class="text-center"><a href="{% url 'admin_panel:task_change_status' task.pk %}"><i class="material-icons light-green-text accent-2">check</i></a></th>
                                    {% else %}
                                        <th class="text-center"><a href="{% url 'admin_panel:task_change_status' task.pk %}"><i class="material-icons deep-orange-text accent-3">check</i></a></th>
                                    {% endif %}
                                    <th class="text-center">{{task.crontab.hour}}:{{task.crontab.minute}}</th>
                                    <th class="text-center">{{task.last_run_at|date:"Y-m-d"}} {{task.last_run_at|time:"H:i"}}</th>
                                    <th class="text-center">{{task.total_run_count}}</th>
                                    {% if task.one_off == False %}
                                        <th class="text-center"><i class="material-icons deep-orange-text accent-3">close</i></th>
                                    {% else %}
                                        <th class="text-center"><i class="material-icons light-green-text accent-2">check</i></th>
                                    {% endif %}
                                    <th class="text-center"><a href="{% url 'admin_panel:task_remove' task.pk %}"><i class="material-icons deep-orange-text accent-3" style="color: #26a69a;">remove</i></a></th>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}