fedor/admin_panel/urls.py
from django.urls import path
from .views import *

app_name = 'admin_panel'
urlpatterns = [
    path('page/', show_admin_page, name="show_admin_page"),
    path('user/create/page/', show_registration_page, name='show_registration_page'),
    path('user/create/', user_registrations, name='create_user'),
    path('user/update/page/<int:user_id>', show_edit_user_page, name='show_edit_user_page'),
    path('user/update/<int:user_id>', update_user_profile, name='update_user_profile'),
    path('user/delete/<int:user_id>', delete_user, name='delete_user'),
    path('schedule/add-page/', schedule_add_page, name='schedule_add_page'),
    path('schedule/add/', schedule_add, name='schedule_add'),
    path('schedule/list/', schedule_list, name='schedule_list'),
    path('schedule/remove/<int:schedule_id>', schedule_remove, name='schedule_remove'),
    path('schedule/update-page/<int:schedule_id>', schedule_update_page, name='schedule_update_page'),
    path('schedule/update/<int:schedule_id>', schedule_update, name='schedule_update'),
    path('task/schedule-list/', task_schedule_list_page, name='task_schedule_list_page'),
    path('task/add-page/', task_add_page, name='task_add_page'),
    path('task/add/algoritm/', task_add_algoritm, name='task_add_algoritm'),
    path('task/remove/<int:task_id>', task_remove, name='task_remove'),
    path('task/change-status/<int:task_id>', task_change_status, name='task_change_status'),
    path('task-user/list/', tasks_user_list, name='tasks_user_list')

]

fedor/api/urls.py
from django.urls import path
from graphene_django.views import GraphQLView
from schema import schema
from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    path('graphql/', csrf_exempt(GraphQLView.as_view(graphiql=True, schema=schema))),
]

fedor/auth_fedor/urls.py
from django.urls import path
from .views import *

app_name = 'auth_fedor'
urlpatterns = [
    path('login/', show_login_page, name="login_page"),
    path('login/on/', user_login, name='user_login'),
    path('logout/', user_logout, name='user_logout')
]

fedor/fedor/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import *

urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('auth/', include('auth_fedor.urls')),
    path('auto/', include('auto_matching.urls')),
    path('admin/', include('admin_panel.urls')),
    path('matching/', include('manual_matching.urls')),
    path('directory/', include('directory.urls')),
    path('analytic/', include('analytic.urls')),
    path('api/', include('api.urls')),
    re_path(r'^', index)
]

fedor/manual_matching/urls.py
from django.urls import path
from .views import *

app_name = 'manual_matching'
urlpatterns = [
    path('manual-matching/page/', show_manual_matching_page, name='show_manual_matching_page'),  # Рендер страницы
    path('manual-matching/page/get/sku/', get_sku, name='get_sku'),  # Выгрузка клиентской номенклатуры
    path('manual-matching/page/get/eas/', get_eas, name='get_eas'),  # Выгрузка ЕАС номенклатуры
    path('manual-matching/match/', match_eas_sku, name='match_eas_sku'),  # Ручной Мэтчинг
    path('final-matching/page/get/', get_final_matching, name='get_final_matching'),  # Выгрузка данных финальной таблицы
    path('final-matching/delete/', delete_match, name='delete_match'),  # Удалить результат мэтчинга и отправить в необработанные
    path('filters-matching/', filter_matching, name='filter_matching'),  # Фильтры ручного мэтчинга
    path('filters-matching/sku/', filter_for_sku_list, name='filter_for_sku_list'),  # Фильтр по СКУ
    path('final-filters/', final_table_filter, name='final_table_filter'),  # Фильтры по таблице
    path('final/all-result-matching/', all_result_matching, name='all_result_matching'),  # Все результаты мэтчинга
    path('filters-by-tn_fv/', re_match_filter, name='re_match_filter'),  # Фильтр в модальном окне ремэтч

]

fedor/fedor/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect

from django.urls import reverse


@login_required
def index(request):
    return HttpResponseRedirect(
        reverse('manual_matching:show_manual_matching_page')
    )

fedor/fedor/templates/access_window.html
<div id="access_window" class="modal">
    <div class="modal-content text-center">
      <h4>Выполнено успешно!</h4>
      <br>
      <p>{( access )}</p>
    </div>
    <div class="modal-footer">
      <a href="#!" class="modal-close waves-effect waves-green btn">Закрыть</a>
    </div>
</div>

fedor/fedor/templates/error_window.html
<div id="error-modal" class="modal">
    <div class="modal-content text-center">
      <h4>Произошла ошибка</h4>
      <br>
      <p>{( error )}</p>
    </div>
    <div class="modal-footer">
      <a href="#!" class="modal-close waves-effect waves-green btn">Закрыть</a>
    </div>
</div>

fedor/fedor/templates/header.html
<nav class="teal">
	<div class="nav-wrapper">
		<a href="#" class="brand-logo">Fedor</a>
		<ul id="nav-mobile" class="right hide-on-med-and-down">
			<li></li>
			<li><p>{{ request.user }}</p></li>
			<li>
				<a href="{% url 'auth_fedor:user_logout' %}"><i class="material-icons">exit_to_app</i></a>
			</li>
		</ul>
	</div>
</nav>

fedor/fedor/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Федор{% endblock %}</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'fedor/css/main.css' %}">
    <link rel="icon" type="image/svg+xml" href="{% static 'fedor/media/favicon.svg' %}">
    {% if request.COOKIES.user_style %}
        {% if request.COOKIES.user_style == 'dark' %}
            <link rel="stylesheet" type="text/css" href="{% static 'fedor/css/dark/materialize-dark.css' %}">
        {% else %}
            <link rel="stylesheet" type="text/css" href="{% static 'fedor/css/classic/materialize-classic.css' %}">
        {% endif %}
    {% else %}
         <link rel="stylesheet" type="text/css" href="{% static 'fedor/css/classic/materialize-classic.css' %}">
    {% endif %}
    <script src="{% static 'fw/vuejs/vue.js' %}"></script>
    <script src="{% static 'fw/axios/dist/axios.min.js' %}"></script>
    {% block custom_css %}{% endblock %}
</head>
<body class="{{ request.COOKIES.body }}">
{% include 'preloader.html' %}
{% block content %}{% endblock %}
{% include 'error_window.html'  %}
{% include 'access_window.html'  %}
{% if request.user.is_authenticated %}
    {% include 'main_menu.html' %}
    {% include 'user_style.html' %}
{% endif %}
</body>
<script src="{% static 'fw/materialize/js/materialize.min.js' %}"></script>
<script src="{% static 'fedor/js/main_menu.js' %}"></script>
<script src="{% static 'fedor/js/show_error_window.js' %}"></script>
<script src="{% static 'fedor/js/show_access_window.js' %}"></script>
<script src="{% static 'fedor/js/show_preloader.js' %}"></script>
{% block competitor %}
<script src="{% static 'fedor/js/number_competitor.js' %}"></script>
{% endblock %}
{% if request.user.is_authenticated %}
    <script src="{% static 'fedor/js/user_style.js' %}"></script>
{% endif %}
{% block script %}{% endblock %}
</html>

fedor/fedor/templates/main_menu.html
{% load static %}
<ul id="slide-out" class="sidenav">
    <li>
        <div class="user-view">
              <div class="background">
                <img src="{% static 'fedor/media/6.jpg' %}">
              </div>
              <a href="#!user"><img class="circle" src="{% static 'fedor/media/FEDOR2.png' %}" style="height: 40%; width: 40%;"></a>
              <a href="#!name"><span class="white-text name">{{ request.user.profile.access_level.level_name }}</span></a>
              <a href="#!email"><span class="white-text email">{{ request.user.first_name }} {{ request.user.last_name }}</span></a>
        </div>
    </li>
    {% if request.user.is_authenticated %}
        {% if request.user.profile.access_level.level == 1 or request.user.profile.access_level.level == 2 or request.user.profile.access_level.level == 3 %}
            <li><a href="{% url 'show_auto_matching_page' %}"><i class="material-icons">autorenew</i>АВТО-МЭТЧИНГ</a></li>
        {% else %}
            <li><a class="subheader"><i class="material-icons">autorenew</i>АВТО-МЭТЧИНГ</a></li>
        {% endif %}
    <li><a href="{% url 'manual_matching:show_manual_matching_page' %}"><i class="material-icons">border_color</i>РУЧНОЙ-МЭТЧИНГ</a></li>
    {% if request.user.profile.access_level.level == 1 or request.user.profile.access_level.level == 2 or request.user.profile.access_level.level == 3 %}
        <li><a href="{% url 'analytic_page' %}"><i class="material-icons">trending_up</i>АНАЛИТИКА</a></li>
    {% else %}
        <li><a class="subheader"><i class="material-icons">trending_up</i>АНАЛИТИКА</a></li>
    {% endif %}
    <li><div class="divider"></div></li>
    {% if request.user.profile.access_level.level == 1 %}
        <li class="f-ml"><a class="subheader"></a>Админ панель</li>
        <li><a class="waves-effect" href="{% url 'admin_panel:show_edit_user_page' user_id=request.user.pk %}"><i class="material-icons">supervisor_account</i>РЕДАКТИРОВАНИЕ</a></li>
        <li><a class="waves-effect" href="{% url 'admin_panel:show_registration_page' %}"><i class="material-icons">local_library</i>РЕГИСТРАЦИЯ</a></li>
        <li><a class="waves-effect" href="{% url 'admin_panel:schedule_list' %}"><i class="material-icons">assignment</i>ПЛАНИРОВЩИК</a></li>
    {% endif %}

    <li style="position: absolute; bottom: 15%; width: 100%;"><div class="divider"></div></li>
    <li style="position: absolute; bottom: 10%; width: 100%;">
        <a class="waves-effect" href="{% url 'auth_fedor:user_logout' %}?next={{request.path}}">
            <i class="material-icons">exit_to_app</i>{{ request.user }}
        </a>
    </li>
    {% endif %}
</ul>

<div id="main_menu_app" class="fedor-menu">
    <a href="#" data-target="slide-out" class="sidenav-trigger" v-on:click="show_menu">
        <i class="small material-icons">menu</i>
    </a>
</div>

fedor/fedor/templates/number_competitor.html
<script src="https://unpkg.com/vue"></script>
<script src="https://unpkg.com/jquery@3.1.1/dist/jquery.js"></script>
<script src="https://unpkg.com/select2@4.0.3/dist/js/select2.js"></script>

<link
  rel="stylesheet"
  type="text/css"
  href="https://unpkg.com/select2@4.0.3/dist/css/select2.min.css"
/>

<script type="text/x-template" id="demo-template">

    <div class="row">
        <div class="row">
            <div class="col s12">
                <div class="chip" v-for="comp in comps" v-if="all_selected==false" >
                     <span maxlength="3">{(comp.name)}</span>
                </div>
            </div>
        </div>
        <div class="row">
              <div class="input-field col s9">
                    <select2 :options="options" v-model="selected">
                      <option disabled value="0">Select one</option>
                    </select2>
                  <a class="waves-effect waves-light btn-small f-mt" v-on:click="del_chip">СБРОС</a>
              </div>
            <div class="col s1 offset-s1">
                <p>
                  <label>
                    <input type="checkbox" v-model="all_selected"/>
                    <span>ВСЕ</span>
                  </label>
                </p>
            </div>
        </div>
    </div>
</script>

<script type="text/x-template" id="select2-template">
      <select>
        <slot></slot>
      </select>
</script>
<div class="row">
    <div class="col s12">
        <div id="number-competitor-app">

        </div>
    </div>
</div>

fedor/fedor/templates/preloader.html
<div class="f-preloader" id="preloader_app" v-if="show_preloading">
    <div class="container f-mt">
        <div class="row z-depth-5">
            <div class="col s12">
                <h5 class="text-center">Загрузка</h5>
               <div class="progress">
                  <div class="indeterminate"></div>
               </div>
                <p class="text-center">Пожалуйста, не выключайте компьютер пока идет загрузка...</p>
            </div>
        </div>
    </div>
</div>

fedor/fedor/templates/user_style.html
{% load static %}
<div class="fixed-action-btn" id="user-style">
  <a class="btn-floating btn-large red">
    <i class="large material-icons">build</i>
  </a>
  <ul>
    <li><a class="btn-floating green" v-on:click="style_change"><i class="material-icons">swap_horiz</i></a></li>
    <li><a class="btn-floating blue" v-on:click="reset_font_size"><i class="material-icons">clear</i></a></li>
    <li>
      <form action="#">
          <p class="range-field" >
            <input type="range" id="test5" min="12" max="30" class="fedor-font-change" v-model="font_size"/>
          </p>
      </form>
    </li>
  </ul>
</div>